### ISSUE TITLE
Install using Nuget Package Manager

### ISSUE THREAD

**Issue by ruddhani** [jtourlamain/DevProtocol.Azure.EntityPropertyConverter#1]
While I am searching for DevProtocol.Azure.EntityPropertyConverter or EntityPropertyConverter in Nuget Package manager in VS 2019, I am not able to search this extension, please help me how to install to my project

**Comment by jtourlamain** [comment]
@ruddhani I never deployed a Nuget package. I only blogged about solving this and provided the code via GitHub.
